ProjetoCadastroMVC/ProjetoContato/Models/ErrorViewModel.cs
namespace ProjetoContato.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ProjetoCadastroMVC/ProjetoContato/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;


namespace ProjetoContato.Controllers;

public class ContatoController : Controller
{

    public IActionResult Index()
    {
        return View();
    }

public IActionResult Criar()
    {
        return View();
    }

    public IActionResult Editar()
    {
        return View();
    }

    public IActionResult ApagarConfirmacao()
    {
        return View();
    }
    
}

ProjetoCadastroMVC/ProjetoContato/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ProjetoContato.Models;

namespace ProjetoContato.Controllers;

public class HomeController : Controller
{

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ProjetoCadastroMVC/ProjetoContato/Views/Contato/ApagarConfirmacao.cshtml
@{
    ViewData["Title"] = "Confirmar exclusão de contato";
}

<div class="text-center">
    <h3 class="text-white">Realmente deseja apagar o contato (Marcos Alan)?</h3>
</div>

<a class="btn btn-primary btn-block" role="button" >Cancelar Exclusão</a>
<a class="btn btn-primary btn-danger btn-block" role="button">Confirmar Exclusão</a>

ProjetoCadastroMVC/ProjetoContato/Views/Contato/Criar.cshtml
@{
    ViewData["Title"] = "Adicionar Contato";
}

<div class="text-center bg-dark">

    <h1 class="display-4" style="color: whitesmoke;">Cadastrar novo contato</h1>

</div>

<form>
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" class="form-control" placeholder="Digite o nome">
    </div>

    <div class="form-group">
        <label for="Email">E-mail</label>
        <input type="text" class="form-control" placeholder="Digite o Email">
    </div>

    <div class="form-group">
        <label for="Celular">Celular</label>
        <input type="text" class="form-control" placeholder="Digite o celular">
    </div>
    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

ProjetoCadastroMVC/ProjetoContato/Views/Contato/Editar.cshtml
@{
    ViewData["Title"] = "Editar contato";
}

<div class="text-center bg-dark">

    <h1 class="display-4" style="color: whitesmoke;">Editar contato</h1>

</div>

<form>
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" class="form-control" placeholder="Digite o nome">
    </div>

    <div class="form-group">
        <label for="Email">E-mail</label>
        <input type="text" class="form-control" placeholder="Digite o Email">
    </div>

    <div class="form-group">
        <label for="Celular">Celular</label>
        <input type="text" class="form-control" placeholder="Digite o celular">
    </div>
    <button type="submit" class="btn btn-primary btn-block">Editar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

ProjetoCadastroMVC/ProjetoContato/Views/Contato/Index.cshtml
@{
    ViewData["Title"] = "Lista de Contatos";
}

<div class="text-center bg-dark">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar novo contato</a>
    </div>
    <br />
    <h1 class="display-4" style="color: whitesmoke;">Listagem de contatos</h1>

    <table class="table" style="color: whitesmoke;">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">E-Mail</th>
                <th scope="col">Celular</th>
                <td></td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>otto@gmail.com</td>
                <td>51 12345-6789</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button" class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a role="button" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Jacob</td>
                <td>thornton@gmail.com</td>
                <td>11 00000-0000</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button" class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a role="button" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Jacob</td>
                <td>teste@gmail.com</td>
                <td>51999999999</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button" class="btn btn-primary" asp-controller="Contato" asp-action="Editar">Editar</a>
                        <a role="button" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>

ProjetoCadastroMVC/ProjetoContato/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial";
}

<div class="text-center">
    <h1 class="display-4 text-white">Bem vindos</h1>
    <p class="text-white"> Bem vindos ao nosso novo site!</p>
</div>

ProjetoCadastroMVC/ProjetoContato/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoContato.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Página inicial</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: red;">
        <div class="container">
            <p class="text-white">&copy; 2023 - ProjetoContato</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>